name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
      
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
          # The name of the image you would like to push
          name: josh-ints
          # The login username for the registry
          username: ${{ secrets.dockerName }}
          # The login password for the registry
          password: ${{ secrets.dockerPass }
          # Use dockerfile when you would like to explicitly build a Dockerfile
          dockerfile: .Dockerfile
        
    - name: Push to DO droplet
      uses: digitalocean/action-doctl@master
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: echo "test"
