name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:

    - name: Update SHA
      run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/site/_meta
      
    - name: Build container image
      run: docker build -t jasonobeid/josh-ints.me:$(echo $GITHUB_SHA | head -c7) .

    - name: Docker Login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Push image to Docker Hub
      run: docker push jasonobeid/josh-ints.me
        
    - name: Push to DO droplet
      uses: digitalocean/action-doctl@master
      env:
        DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      with:
        args: echo "test"